### ISSUE TITLE
No Longer Works in UE5?

### ISSUE THREAD

**Issue by Dealman** [JanKXSKI/AssetTutorialPlugin#1]
First off I wanna say thanks for the tutorial, by far the most detailed one out there on how to do this.

However, it seems like some things may have changed? I get stuck on the **Registering the Asset Type Actions** step.

The method `RegisterAssetTypeActions()` seems to expect another parameter now - one that implements `IAssetTypeActions`, however, even though I changed my Action class to implement this interface instead of `FAssetTypeActions_Base` - I still get the same error;

`Cannot convert rvalue of type TSharedRef<FChartAssetTypeActions, ESPMode::ThreadSafe> to parameter type TSharedRef<IAssetTypeActions>`

My current `StartupModule()` code is as follows;
```cpp
void FMyEditorModule::StartupModule()
{
	MyAssetTypeActions = MakeShared<FMyAssetTypeActions>();
	FAssetToolsModule::GetModule().Get().RegisterAssetTypeActions(MyAssetTypeActions.ToSharedRef());
}
```

Version is `UE5.0.3`.

I'm still fairly new to C++, let alone Unreal's version of it. Haven't been able to solve this error yet, but will update this issue if I do.

**Comment by Dealman** [comment]
Was a silly error on my part, wish my IDE had helped point me in the right direction. Completely forgot to make the inheritance of `IAssetTypeActions` public. 🤦‍♂️ 

I found it while looking through your Concord repository, which also made me realize you're doing things a fair bit differently in there. Is that the recommended way of registering these kind of things now, or?

**Comment by JanKXSKI** [comment]
Hey, happy to hear the tutorial was useful to you! I've run into the same error in the past, the compiler isn't exactly direct about what is missing... glad to hear you figured it out.

Concord has a few more bells and whistles, but the pattern for custom assets is the same: register asset type actions and provide a factory class. For example the asset type actions of a Concord model are declared here: https://github.com/JanKXSKI/Concord/blob/main/Source/ConcordEditor/Private/ConcordModelActions.h
