### ISSUE TITLE
UE4 4.27 Issue

### ISSUE THREAD

**Issue by 9wind** [JanKXSKI/AssetTutorialPlugin#2]
Hi. Thank you for your tutorial. I've tried to search for a good instruction related to asset creation preferably in 4.27. I followed all initial steps but I am getting errors in Editor itself on Start/Shutdown module. 
![x](https://user-images.githubusercontent.com/36643825/187322974-c6ba5ae2-ad52-43a9-8684-75ae8d560f3a.png)

**Comment by JanKXSKI** [comment]
Hey! Thanks for checking out the tutorial. Note that I put it together for 5.0, so no guarantees that it's going to work on 4.27, sorry.

The error squiggles in your screenshot suggests that the "NormalDistributionAssetTypeActions" member of the "FAssetTutorialPluginEditorModule" is not correctly declared in "AssetTutorialEditor.h".

Hope this helps!

**Comment by 9wind** [comment]
I had to restart and refresh the files. It works (custom asset type in
4.27). Thank you for your tutorial.

**Comment by JanKXSKI** [comment]
Oh great, good to hear 👍
